In [25]:
import numpy as np
import pandas as pd

In [26]:
pd.read_csv('time_series_covid19_confirmed_global.csv')
pd.read_csv("time_series_covid19_deaths_global.csv")

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [27]:
index_val=[('csc',2019),('csc',2020),('csc',2021),('csc',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a=pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a
# in this series has one problem we cant fatch all csc items at onces

(csc, 2019)    1
(csc, 2020)    2
(csc, 2021)    3
(csc, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [28]:
# solution => multiindex series (also known  as hierarchical indexing)
# multiple index levels within single index

In [29]:
# how to create multiindex series
#1. pd.MultiIndex.from_tuple()
index_val=[('csc',2019),('csc',2020),('csc',2021),('csc',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiind=pd.MultiIndex.from_tuples(index_val)
multiind

MultiIndex([('csc', 2019),
            ('csc', 2020),
            ('csc', 2021),
            ('csc', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [30]:
# 2. pd.MultiIndex.from_product(index_val)
mulp=pd.MultiIndex.from_product([['csc','ece'],[2019,2020,2021,2022]])
mulp

MultiIndex([('csc', 2019),
            ('csc', 2020),
            ('csc', 2021),
            ('csc', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [31]:
s=pd.Series([1,2,3,4,5,6,7,8],index=multiind)
s

csc  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [32]:
s['csc']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [33]:
# unstack:- it convert multiindex series in dataframe
temp=s.unstack()
temp

     2019  2020  2021  2022
csc     1     2     3     4
ece     5     6     7     8

In [34]:
# stack :- it reconvert it into multindex series
temp.stack()

csc  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [37]:
# why we create series even we can handle it with dataframe
# because it conver higgher dimention data into lower diamention data

In [38]:

# multiindex dataframe

In [40]:
df1=pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15,16]],index=multiind,columns=['avg_packeg','student'])
df1

          avg_packeg  student
csc 2019           1        2
    2020           3        4
    2021           5        6
    2022           7        8
ece 2019           9       10
    2020          11       12
    2021          13       14
    2022          15       16

In [41]:
df1.loc['csc']

      avg_packeg  student
2019           1        2
2020           3        4
2021           5        6
2022           7        8