In [1]:
import numpy as np
import pandas as pd

In [3]:
# what are vectorized operations
a=np.array([1,2,3,4])
a*3   # in vectorized operation is performed single operation on whole list or array

array([ 3,  6,  9, 12])

In [6]:
# problem in vectorized operation in vanilla python
s=['cat','mat',None,'rat']
[i.startswith('c') for i in s]# because of none its cant run and it takes too much time

AttributeError: 'NoneType' object has no attribute 'startswith'

In [ ]:
r=pd.Series(['cat','mat',None,'rat'])
r.str.startswith('c')# fast and optimized

0     True
1    False
2     None
3    False
dtype: object

In [11]:
titanic=pd.read_csv('titanic.csv')
titanic['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [20]:
# common function
# lower/higher/capitalize/title
titanic['Name'].str.lower()
#len
titanic['Name'][titanic['Name'].str.len()==82].values[0]
# strip
titanic['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [29]:
# split =>get
titanic['last_name']=titanic['Name'].str.split(',').str.get(0)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen

In [32]:
titanic [['title','first_name']]=titanic['Name'].str.split(',').str.get(1).str.strip().str.split(' ',n=1,expand=True)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [33]:
titanic['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [36]:
# replace
titanic['title']=titanic['title'].str.replace('Ms.','Miss.')
titanic['title']=titanic['title'].str.replace('Mlle.','Miss.')

In [37]:
titanic['title'].value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Lady.          1
Mme.           1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [41]:
# filtering
# startswith/endswith
titanic[titanic['first_name'].str.startswith('A')]
# isdigit/isalpha
titanic[titanic['Name'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, last_name, title, first_name]
Index: []

In [43]:
# apply ragex
#contain
# search john => both case
titanic[titanic['first_name'].str.contains('john',case=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S,Turpin,Mrs.,William John Robert (Dorothy Ann Wonnacott)
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S,Rogers,Mr.,William John
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S,Doling,Mrs.,John T (Ada Julia Bone)
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S,Barton,Mr.,David John
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,NaN,S,Turpin,Mr.,William John Robert
160,161,0,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,NaN,S,Cribb,Mr.,John Hatfield
162,163,0,3,"Bengtsson, Mr. John Viktor",male,26.0,0,0,347068,7.7750,NaN,S,Bengtsson,Mr.,John Viktor
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S,Goldsmith,Master.,"Frank John William ""Frankie"""
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,Baumann,Mr.,John D
188,189,0,3,"Bourke, Mr. John",male,40.0,1,1,364849,15.5000,NaN,Q,Bourke,Mr.,John
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S,Perkin,Mr.,John Henry
226,227,1,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5000,NaN,S,Mellors,Mr.,William John
227,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.2500,NaN,S,Lovell,Mr.,"John Hall (""Henry"")"
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,Sage,Mr.,George John Jr
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mrs.,Frank John (Emily Alice Brown)
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,NaN,S,Adams,Mr.,John
418,419,0,2,"Matthews, Mr. William John",male,30.0,0,0,28228,13.0000,NaN,S,Matthews,Mr.,William John
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S,Smart,Mr.,John Montgomery
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,Farthing,Mr.,John
548,549,0,3,"Goldsmith, Mr. Frank John",male,33.0,1,1,363291,20.5250,NaN,S,Goldsmith,Mr.,Frank John
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S,Davies,Master.,John Morgan Jr
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.0,0,2,17421,110.8833,C70,C,Thayer,Mr.,John Borland Jr
563,564,0,3,"Simmons, Mr. John",male,NaN,0,0,SOTON/OQ 392082,8.0500,NaN,S,Simmons,Mr.,John
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S,Flynn,Mr.,"John Irwin (""Irving"")"
574,575,0,3,"Rush, Mr. Alfred George John",male,16.0,0,0,A/4. 20589,8.0500,NaN,S,Rush,Mr.,Alfred George John
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C,Thayer,Mrs.,John Borland (Marian Longstreth Morris)
583,584,0,1,"Ross, Mr. John Hugo",male,36.0,0,0,13049,40.1250,A10,C,Ross,Mr.,John Hugo
586,587,0,2,"Jarvis, Mr. John Denzil",male,47.0,0,0,237565,15.0000,NaN,S,Jarvis,Mr.,John Denzil
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26.0000,NaN,S,Chapman,Mr.,John Henry
613,614,0,3,"Horgan, Mr. John",male,NaN,0,0,370377,7.7500,NaN,Q,Horgan,Mr.,John
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S,Bowen,Mr.,"David John ""Dai"""
657,658,0,3,"Bourke, Mrs. John (Catherine)",female,32.0,1,1,364849,15.5000,NaN,Q,Bourke,Mrs.,John (Catherine)
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S,Weir,Col.,John
698,699,0,1,"Thayer, Mr. John Borland",male,49.0,1,1,17421,110.8833,C68,C,Thayer,Mr.,John Borland
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,Astor,Mrs.,John Jacob (Madeleine Talmadge Force)
733,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S,Berriman,Mr.,William John
760,761,0,3,"Garfirth, Mr. John",male,NaN,0,0,358585,14.5000,NaN,S,Garfirth,Mr.,John
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S,Hogeboom,Mrs.,John C (Anna Andrews)
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.0,0,0,C 7075,6.4500,NaN,S,Holm,Mr.,John Fredrik Alexander
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S,Reuchlin,Jonkheer.,John George
825,826,0,3,"Flynn, Mr. John",male,NaN,0,0,368323,6.9500,NaN,Q,Flynn,Mr.,John
848,849,0,2,"Harper, Rev. John",male,28.0,0,1,248727,33.0000,NaN,S,Harper,Rev.,John
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,Gill,Mr.,John William

In [45]:
# find lastname starts eith vowel and end with vowel
titanic[titanic['last_name'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Uruchurtu,Don.,Manuel E
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Albimona,Mr.,Nassef Cassem
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ali,Mr.,Ahmed
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mr.,Josef
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr.,Ramon
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S,Angle,Mrs.,"William A (Florence ""Mary"" Agnes Hughes)"
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Ali,Mr.,William
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Alhomaki,Mr.,Ilmari Rudolf

# datetime
### Timestamp object
time stamps reference particular moment in time (e.g., oct 24th,2022 at 9:00 pm)

In [47]:
# creating a timestamp
pd.Timestamp('2025/4/2')

Timestamp('2025-04-02 00:00:00')

In [54]:
# variation
pd.Timestamp('2025-4-2')
pd.Timestamp('2025, 4, 2')

Timestamp('2025-04-02 00:00:00')

In [49]:
# only year
pd.Timestamp('2025')

Timestamp('2025-01-01 00:00:00')

In [50]:
# using text
pd.Timestamp('2nd April 2025')

Timestamp('2025-04-02 00:00:00')

In [56]:
pd.Timestamp('2025-4-2-9:23PM')

Timestamp('2025-04-02 21:23:00')

In [60]:
# using datetime .datetime object in python
import datetime as dt
x=pd.Timestamp(dt.datetime(2025, 4, 3, 9 ,44))

In [64]:
# fatching attributes
x.year
x.month
x.day
x.hour
x.minute

44

In [65]:
# why seperates object to handle data and time when python already has datetime function

1. syntax wise datetime is very convenient
2. but the performance takes a hit while working with huge data. List vs Numpy Array
3. the weakness of python's datetime format inspired the Numpy team to add a set of native time series data type to Numpt.
4. the datetime64 dtype encodes dates as 64-bit integers, and thus allows of dates to be represented very compactly

In [ ]:
date=np.array('2025-04-03', dtype=np.datetime64)
date

array('2025-04-03', dtype='datetime64[D]')

In [ ]:
# vectorized operation
date + np.arange(12)
date

array('2025-04-03', dtype='datetime64[D]')

1. because of the uniform type in Numpy datetime64 arrays this type of operation can be accomplished much more quickly than if we were working directly with python's datetime objects, especially as arrays get large
2. pandas timestampobject combines the ease-ofuse of python datetime with the effifient storage and vectorize interface of numpy.datetime64
3. from a group of these timestamp object, pandas can construct a datetimeindex that can be used to index in a series or dataframe

### DatetimeIndex object

a collection of pandas timestamp

In [86]:
pd.DatetimeIndex(['2025-3-3','2023-4-4','2025-5-5'])

DatetimeIndex(['2025-03-03', '2023-04-04', '2025-05-05'], dtype='datetime64[ns]', freq=None)

In [87]:
# using python datetime object
pd.DatetimeIndex([dt.datetime(2023,2,3),dt.datetime(2023,2,3),dt.datetime(2023,2,3)])

DatetimeIndex(['2023-02-03', '2023-02-03', '2023-02-03'], dtype='datetime64[ns]', freq=None)

In [91]:
# from timestamp
dtin=pd.DatetimeIndex([pd.Timestamp(2023,2,23),pd.Timestamp(2023,2,24),pd.Timestamp(2023,2,25)])

In [92]:
# using datetime insex as series
pd.Series([1,2,3],index=dtin)

2023-02-23    1
2023-02-24    2
2023-02-25    3
dtype: int64

In [94]:
#date range function
pd.date_range(start='2025-4-3',end='2025-4-30')

DatetimeIndex(['2025-04-03', '2025-04-04', '2025-04-05', '2025-04-06',
               '2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10',
               '2025-04-11', '2025-04-12', '2025-04-13', '2025-04-14',
               '2025-04-15', '2025-04-16', '2025-04-17', '2025-04-18',
               '2025-04-19', '2025-04-20', '2025-04-21', '2025-04-22',
               '2025-04-23', '2025-04-24', '2025-04-25', '2025-04-26',
               '2025-04-27', '2025-04-28', '2025-04-29', '2025-04-30'],
              dtype='datetime64[ns]', freq='D')

In [96]:
# altenate dates
pd.date_range(start='2025-4-3',end='2025-4-30',freq='3D')

DatetimeIndex(['2025-04-03', '2025-04-06', '2025-04-09', '2025-04-12',
               '2025-04-15', '2025-04-18', '2025-04-21', '2025-04-24',
               '2025-04-27', '2025-04-30'],
              dtype='datetime64[ns]', freq='3D')

In [97]:
# business bays
pd.date_range(start='2025-4-3',end='2025-4-30',freq='B')

DatetimeIndex(['2025-04-03', '2025-04-04', '2025-04-07', '2025-04-08',
               '2025-04-09', '2025-04-10', '2025-04-11', '2025-04-14',
               '2025-04-15', '2025-04-16', '2025-04-17', '2025-04-18',
               '2025-04-21', '2025-04-22', '2025-04-23', '2025-04-24',
               '2025-04-25', '2025-04-28', '2025-04-29', '2025-04-30'],
              dtype='datetime64[ns]', freq='B')

In [102]:
# week days
pd.date_range(start='2025-4-3',end='2026-4-30',freq='W-THU')

DatetimeIndex(['2025-04-03', '2025-04-10', '2025-04-17', '2025-04-24',
               '2025-05-01', '2025-05-08', '2025-05-15', '2025-05-22',
               '2025-05-29', '2025-06-05', '2025-06-12', '2025-06-19',
               '2025-06-26', '2025-07-03', '2025-07-10', '2025-07-17',
               '2025-07-24', '2025-07-31', '2025-08-07', '2025-08-14',
               '2025-08-21', '2025-08-28', '2025-09-04', '2025-09-11',
               '2025-09-18', '2025-09-25', '2025-10-02', '2025-10-09',
               '2025-10-16', '2025-10-23', '2025-10-30', '2025-11-06',
               '2025-11-13', '2025-11-20', '2025-11-27', '2025-12-04',
               '2025-12-11', '2025-12-18', '2025-12-25', '2026-01-01',
               '2026-01-08', '2026-01-15', '2026-01-22', '2026-01-29',
               '2026-02-05', '2026-02-12', '2026-02-19', '2026-02-26',
               '2026-03-05', '2026-03-12', '2026-03-19', '2026-03-26',
               '2026-04-02', '2026-04-09', '2026-04-16', '2026-04-23',
               '2026-04-30'],
              dtype='datetime64[ns]', freq='W-THU')

In [104]:
pd.date_range(start='2025-4-3',end='2025-4-30',freq="6H")

C:\Users\ankit\AppData\Local\Temp\ipykernel_19668\4216033540.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2025-4-3',end='2025-4-30',freq="6H")

DatetimeIndex(['2025-04-03 00:00:00', '2025-04-03 06:00:00',
               '2025-04-03 12:00:00', '2025-04-03 18:00:00',
               '2025-04-04 00:00:00', '2025-04-04 06:00:00',
               '2025-04-04 12:00:00', '2025-04-04 18:00:00',
               '2025-04-05 00:00:00', '2025-04-05 06:00:00',
               ...
               '2025-04-27 18:00:00', '2025-04-28 00:00:00',
               '2025-04-28 06:00:00', '2025-04-28 12:00:00',
               '2025-04-28 18:00:00', '2025-04-29 00:00:00',
               '2025-04-29 06:00:00', '2025-04-29 12:00:00',
               '2025-04-29 18:00:00', '2025-04-30 00:00:00'],
              dtype='datetime64[ns]', length=109, freq='6h')

In [105]:
# for month end=> M
# for month stering => MS
# for year end => A

In [106]:
# period 
pd.date_range(start='2025-4-3',periods=20)

DatetimeIndex(['2025-04-03', '2025-04-04', '2025-04-05', '2025-04-06',
               '2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10',
               '2025-04-11', '2025-04-12', '2025-04-13', '2025-04-14',
               '2025-04-15', '2025-04-16', '2025-04-17', '2025-04-18',
               '2025-04-19', '2025-04-20', '2025-04-21', '2025-04-22'],
              dtype='datetime64[ns]', freq='D')

In [107]:
# to_datetime function 
# convert an existing object to pandas timestamp/tatetimeindex object

In [110]:
# simple series exapmle
s=pd.Series(['2032-4-4','2034-3-3','2034-2-2'])
pd.to_datetime(s).dt.month_name()

0       April
1       March
2    February
dtype: object

In [111]:
# with error
e=pd.Series(['2022-2-2','2023-3-3','2023-333-2'])
pd.to_datetime(e,errors='coerce')

0   2022-02-02
1   2023-03-03
2          NaT
dtype: datetime64[ns]